### PR TITLE
improve the answer about closure

### PR DESCRIPTION
**Pull request by nicholaslee119**
refernces
https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch5.md

### CODE REVIEW

**Comment by yangshun** [comment]
The additional line added does not do a better job of elaborating on closures than the existing answer. Which part of the existing answer is unclear?

**Comment by nicholaslee119** [comment]
The existing answer did not have an example of how to describe a closure. The conception of the closure includes function and scope, I want to make it clearer by this example.

**Comment by yangshun** [comment]
I feel that this line: 

> If we talk about closure, we should mention a function and a scope, because closure is a kind of relationship between function and scope

does not do a better job explaining than the first line:

> A closure is the combination of a function and the lexical environment within which that function was declared.

**Comment by nicholaslee119** [comment]
OK, I agree with that, I will close this

**Comment by yangshun** [comment]
Thanks for your understanding 😄

**Pull request closed without merging**
