### PR TITLE
Fix mistakes in resume section

### PR DESCRIPTION
**Pull request by dainvinc**
Made a couple of commits reflecting minor grammatical errors.

### CODE REVIEW

**Comment by yangshun** [comment]
Sorry what's a vishal?

**Comment by dainvinc** [comment]
Sorry about that! It was auto-added and I wasn't paying attention to it.

**Comment by louietyj** [comment]
I don't think Github has such a feature of auto-populating your name on a new pull request :)

**Comment by dainvinc** [comment]
It does grab the branch name as the default PR title

**Pull request merged**
