### PR TITLE
Add lonely number problem

### PR DESCRIPTION
**Pull request by jorgegonzalez**

### CODE REVIEW

**Comment by yangshun** [comment]
Thank you for your contribution! More PRs are welcome! It's a good way to contribute to [Hacktoberfest](https://hacktoberfest.digitalocean.com/) 😎

**Comment by yangshun** [comment]
I merged too fast, but I think you meant a space of O(1) instead of running time?

**Comment by jorgegonzalez** [comment]
Sorry! Yes I meant O(1) space.

**Comment by yangshun** [comment]
No worries I'll fix it 😄

**Pull request merged**
