### PR TITLE
Add two questions under hired section

### PR DESCRIPTION
**Pull request by Debajyotighosh654**

### CODE REVIEW

**Comment by yangshun** [comment]
@Debajyotighosh654 where did you get these questions from?

**Comment by Debajyotighosh654** [comment]
> @Debajyotighosh654 where did you get these questions from?

@yangshun  These questions were asked to me in a job interview and you can google these questions.

**Comment by yangshun** [comment]
> > @Debajyotighosh654 where did you get these questions from?
> 
> @yangshun These questions were asked to me in a job interview and you can google these questions.

Were they asked by Hired? Hired is a company and we're adding questions asked by that company.

**Comment by Debajyotighosh654** [comment]
> > > @Debajyotighosh654 where did you get these questions from?
> > 
> > 
> > @yangshun These questions were asked to me in a job interview and you can google these questions.
> 
> Were they asked by Hired? Hired is a company and we're adding questions asked by that company.

oops, sorry my bad. I did it wrong.

**Comment by yangshun** [comment]
Np, closing this then.

**Pull request closed without merging**
