### PR TITLE
Update behavioral-interview-questions.md

### PR DESCRIPTION
**Pull request by MarkMoretto**
Airbnb is a horrible company with shady business practices that are unfavorable to the common traveller.  This pull request is to tweak this otherwise fantastic document to put fewer eyes on the lodging broker.  Anyone with a grain of ethics and integrity wouldn't want to work there, anyway, as it would be huge conflict of interest.

### CODE REVIEW

**Review by dileeppandey — COMMENTED** [review]
I do not think the aim of this repo is to get into the politics of which companies are ethical and which aren't and what constitutes a conflict of interest in tech. This is for knowledge and helping people prepare for interviews. Please use your social media to influence people from not joining instead of removing information that can be helpful to those who want to work there. 

### Please close this.

**Comment by MarkMoretto** [comment]
@dileeppandey Thanks for sharing your thoughts.

Let's **keep it open**, thanks.

There's plenty of other, well-meaning companies out there and removing the company from the list of companies presented in this guide is a zero-loss action.

If you support these kind of corporate ethics, I hope you eventully change your viewpoint :-)

**Comment by iandouglas** [comment]
I agree with @dileeppandey ... the point of this guide isn't to lean toward/away from particular companies, and just to help people prepare for interviews. Personally, if we go down this road, we should scrub all mention of other companies to avoid any sense of whether the maintainers approve or not of any particular company.

That said, i think it's worth KEEPING information like "summer/fall of 2021, both Amazon and Facebook announced that they are no longer asking DP problems" for those kinds of mentions.

**Comment by iandouglas** [comment]
@MarkMoretto perhaps one compromise here would be to take all of the company names out of this document and instead rank these questions based on soft skills like teamwork, communication, leadership, etc.? Taking out an entire company's questions because you don't approve of them means we're losing questions that could still be good to practice. Personally I'm not a fan of Amazon, but their behavioral questions are still valuable to practice.

**Comment by MarkMoretto** [comment]
Yes, then remove the jobs section since this is a tech tutorial, not
careers platform. There's numerous, dedicated websites for that.

**Pull request closed without merging**
